const randomData = {
    randomUsernames: [
        "johnDoe92", "annaSmith", "markJones", "lilyBrown", "davidWilson", 
        "susanClark", "michaelLee", "emilyMiller", "chrisTaylor", "lucyDavis", 
        "tommyKnight", "kellyGreen", "rogerWhite", "oliviaBrown", "sarahLewis", 
        "paulAdams", "victorMartin", "victoriaRiley", "lindaCarter", "georgeMoore"
      ],
      randomEmails: [
        "john@ex.com", "anna.smith@example.com", "mark.jones@example.com", 
        "lily.brown@example.com", "david.wilson@example.com", "susan.clark@example.com", 
        "michael.lee@example.com", "emily.miller@example.com", "chris.taylor@example.com", 
        "lucy.davis@example.com", "tommy.knight@example.com", "kelly.green@example.com", 
        "roger.white@example.com", "olivia.brown@example.com", "sarah.lewis@example.com", 
        "paul.adams@example.com", "victor.martin@example.com", "victoria.riley@example.com", 
        "linda.carter@example.com", "george.moore@example.com"
      ],
    Password: 'test',
    randomEventTitle: [
        "Tech Conference 2025", "Data Science Workshop", "AI Innovations Summit", "Frontend Development Bootcamp", "Annual Developer Meetup",
        "Blockchain for Beginners", "UX/UI Design Seminar", "Cybersecurity Trends", "Machine Learning Fundamentals", "Digital Marketing Workshop"
    ],
    randomEventDescriptions: [
        "This conference brings together the most innovative minds in technology, creating an opportunity for professionals, enthusiasts, and industry leaders to discuss the future of AI, blockchain, and other emerging technologies. As technology continues to evolve at an exponential rate, industries are increasingly turning to artificial intelligence and blockchain to transform their operations. AI has the potential to revolutionize sectors like healthcare, finance, logistics, and customer service, and this conference aims to explore the full range of possibilities. Attendees will have the chance to hear from keynote speakers who are pioneers in AI, blockchain, and other cutting-edge technologies. These thought leaders will share their insights into how AI is being used to automate processes, analyze big data, and create smarter systems. Blockchain, with its decentralized nature, is also gaining traction in industries such as banking, supply chain management, and real estate, offering greater security and transparency. This conference will provide a comprehensive overview of how these technologies are currently being applied, and more importantly, the future potential they hold. In addition to keynote speeches, there will be panel discussions, workshops, and networking opportunities, where participants can engage with experts and peers, share their experiences, and learn about the latest trends and developments. Whether you're looking to gain a deeper understanding of how AI and blockchain can impact your business, or you're simply passionate about emerging tech, this conference promises to offer valuable knowledge and inspire new ideas.",
        
        "This interactive workshop focuses on hands-on data science projects, helping participants understand the tools and methods used in modern data analysis. The world of data science is vast and growing, encompassing everything from data cleaning and processing to building predictive models and generating insights from large datasets. In this workshop, participants will work on real-world projects, learning how to use popular programming languages such as Python and R, along with frameworks like TensorFlow and PyTorch to analyze and interpret data. The workshop will start with an introduction to the fundamentals of data science, covering topics like data exploration, data visualization, and statistical analysis. Participants will learn how to collect and clean data, which is often one of the most time-consuming tasks in the data science process. Then, they will move on to more advanced topics like machine learning, building algorithms that can predict trends, detect anomalies, and even make decisions based on historical data. The workshop is designed for people of all skill levels, from beginners with no prior knowledge of data science to experienced professionals looking to expand their skill set. Experienced instructors will guide attendees through each project, offering tips and advice to help them succeed. By the end of the workshop, participants will have a solid understanding of the key principles of data science, as well as the hands-on experience needed to apply them in real-world scenarios. Whether you're looking to start a career in data science or simply want to enhance your existing skills, this workshop is the perfect opportunity to learn and grow in this fast-evolving field.",
        
        "The AI Innovations Summit brings together experts in artificial intelligence to discuss the latest breakthroughs, trends, and challenges in the field. AI is transforming industries worldwide, from healthcare to manufacturing, and this summit aims to explore the diverse applications and future of this powerful technology. The summit will feature keynote speeches from renowned AI researchers and thought leaders who will share their insights on the cutting-edge developments in AI, including natural language processing, computer vision, and reinforcement learning. Attendees will learn how AI is being used to solve complex problems, automate tasks, and create intelligent systems that can enhance human capabilities. In addition to the keynote presentations, there will be panel discussions where experts will debate the ethical implications of AI, including issues like privacy, bias, and the impact on employment. The summit will also highlight successful case studies, showing how AI is being implemented across various industries to improve efficiency, reduce costs, and provide better services to customers. Throughout the summit, attendees will have the chance to network with AI professionals, share ideas, and collaborate on future projects. Whether you're an AI researcher, a business leader, or someone simply interested in the potential of artificial intelligence, this summit promises to offer valuable insights into the future of AI and its impact on society.",
        
        "This comprehensive bootcamp is designed for frontend developers who want to learn the latest technologies, tools, and best practices for building modern web applications. Frontend development is a rapidly evolving field, with new frameworks, libraries, and design patterns emerging constantly. In this bootcamp, participants will gain hands-on experience with the most popular frontend technologies, including HTML, CSS, JavaScript, React, Angular, and Vue.js. The bootcamp will start with a solid foundation in the core principles of web development, including semantic HTML, responsive design, and accessibility. From there, attendees will dive into more advanced topics like single-page applications, state management, and component-based architectures. They will also learn how to integrate frontend applications with backend APIs, work with RESTful services, and optimize performance for fast-loading web pages. Throughout the bootcamp, participants will work on real-world projects, building fully functional web applications that they can showcase in their portfolios. Experienced instructors will guide attendees through each project, providing feedback and support to ensure that they fully understand the concepts and techniques being taught. By the end of the bootcamp, participants will have the skills and confidence needed to build high-quality, modern web applications from scratch, and will be ready to take on new challenges in the fast-paced world of frontend development.",
        
        "The Annual Developer Meetup is an event where developers of all skill levels come together to network, share ideas, and collaborate on exciting projects. This event has become one of the most anticipated gatherings in the tech community, providing a platform for developers to connect with peers, mentors, and industry leaders. The meetup will feature a variety of activities, including talks, panel discussions, and workshops on a range of topics relevant to developers, from new programming languages and frameworks to best practices in coding and software development. There will also be plenty of time for informal networking, allowing attendees to meet like-minded individuals and explore potential collaborations. One of the highlights of the meetup is the 'hackathon' event, where developers team up to work on projects, solve challenges, and build prototypes in a limited amount of time. Whether you're a junior developer just starting out in your career or a seasoned veteran with years of experience, this meetup offers something for everyone. You’ll have the chance to learn new skills, expand your knowledge, and get inspired by the innovative ideas of others. In addition to the technical sessions, there will also be social events and opportunities to relax and unwind, making this meetup a great way to build relationships within the tech community. Don't miss out on this fantastic opportunity to meet new people, learn new things, and stay up to date with the latest trends in software development.",
        
        "This beginner-friendly session is designed to introduce blockchain technology, exploring its fundamental concepts, how it works, and the potential applications it has across various industries. Blockchain is a decentralized, distributed ledger that allows for secure and transparent record-keeping without the need for intermediaries. In this session, participants will learn about the core components of blockchain, including blocks, transactions, miners, and consensus mechanisms. The session will also cover the different types of blockchains, such as public, private, and consortium blockchains, and how they are used in real-world scenarios. One of the most well-known applications of blockchain is cryptocurrency, with Bitcoin and Ethereum being the most famous examples. However, blockchain technology has far-reaching potential beyond cryptocurrencies, including supply chain management, voting systems, healthcare data management, and intellectual property protection. Throughout the session, participants will gain hands-on experience with basic blockchain concepts and will have the opportunity to participate in discussions about the challenges and opportunities blockchain presents. Whether you're looking to understand the basics of blockchain or considering how it might be applied to your own industry, this session will provide you with a solid foundation and the tools to get started.",
        
        "This seminar will cover the latest trends in UX/UI design, focusing on how design impacts user experiences and influences the success of digital products. UX/UI design is a crucial part of the development process, as it directly affects how users interact with and perceive a product. In this seminar, attendees will explore the key principles of user experience (UX) and user interface (UI) design, including usability, accessibility, and responsive design. The seminar will also cover emerging trends in the field, such as design systems, microinteractions, and user-centered design. Participants will learn how to create intuitive and visually appealing designs that provide seamless experiences across different devices and platforms. The seminar will feature case studies from successful design projects, showcasing how good UX/UI design can improve customer satisfaction, increase conversions, and drive business success. Throughout the seminar, attendees will have the chance to engage in hands-on activities, such as wireframing, prototyping, and testing, to gain practical skills in UX/UI design. Whether you're a seasoned designer looking to stay up to date with the latest trends or someone new to the field, this seminar will provide valuable insights into creating exceptional user experiences and the role of design in shaping the future of digital products.",
        
        "This session will delve into the latest trends in cybersecurity, highlighting the importance of protecting businesses from a wide range of online threats. As technology evolves and more business processes move online, cybersecurity has become a critical concern for organizations of all sizes. Cyberattacks are becoming more sophisticated and frequent, making it essential for businesses to stay ahead of potential risks. In this session, attendees will learn about the latest cybersecurity threats, including phishing attacks, ransomware, data breaches, and insider threats. The session will also cover the best practices for securing networks, systems, and sensitive data, including encryption, multi-factor authentication, and intrusion detection systems. Additionally, the session will explore the importance of employee training in preventing cyberattacks and the role of a strong cybersecurity culture in protecting business assets. Experts will discuss the current landscape of cybersecurity, emerging threats, and the future of digital security. Whether you're responsible for securing your organization’s infrastructure or simply looking to improve your personal security online, this session will provide valuable insights into protecting your business from the ever-evolving world of cyber threats.",
        
        "This course is designed to teach the fundamentals of machine learning, explaining how algorithms work and how they can be applied to real-world problems. Machine learning is a subset of artificial intelligence that enables computers to learn from data and make predictions or decisions without being explicitly programmed. In this course, participants will learn about the different types of machine learning, including supervised, unsupervised, and reinforcement learning, as well as the mathematical and statistical foundations behind these methods. The course will also cover popular machine learning algorithms such as decision trees, linear regression, and neural networks, and explain how to train and test these models using real-world datasets. Participants will have the chance to apply their knowledge through hands-on exercises, where they will work with data to build and evaluate machine learning models. By the end of the course, participants will have a solid understanding of machine learning concepts and techniques, and will be equipped to apply these skills to solve problems in fields like finance, healthcare, and marketing.",
        
        "This digital marketing workshop is aimed at helping marketers stay ahead of the curve by learning the latest strategies, tools, and techniques in the field. Digital marketing is constantly evolving, with new trends, platforms, and technologies emerging all the time. In this workshop, participants will learn how to leverage the power of social media, search engine optimization (SEO), content marketing, email marketing, and paid advertising to reach their target audience and drive business growth. The workshop will cover key topics like how to create compelling content that resonates with customers, how to build a strong online brand presence, and how to use analytics to measure the success of marketing campaigns. Attendees will also learn about emerging digital marketing trends, such as influencer marketing, voice search, and artificial intelligence, and how these trends are reshaping the marketing landscape. Throughout the workshop, participants will work on real-world case studies, developing actionable strategies they can implement in their own businesses. Whether you're new to digital marketing or an experienced marketer looking to enhance your skills, this workshop will provide the knowledge and tools needed to succeed in the fast-paced world of online marketing."
    ],
    randomEventTypes: [
        "Conference", "Workshop", "Seminar", "Bootcamp", "Meetup", "Summit", "Webinar", "Panel Discussion", "Training Session", "Networking Event"
    ],
    randomEventLocations: [
        "San Francisco, CA", "New York, NY", "Los Angeles, CA", "Chicago, IL", "Austin, TX", "Seattle, WA", "Boston, MA", "London, UK", "Berlin, DE", "Sydney, AU"
    ],
    randomEventComments: [
        "Looking forward to learning new things about AI and machine learning in this exciting tech conference!",
        "This data science workshop was incredibly informative, and I learned valuable hands-on techniques that I can apply immediately.",
        "Excited to meet industry leaders at the AI summit and discuss cutting-edge developments in artificial intelligence.",
        "I’m really excited for this bootcamp to expand my knowledge of frontend frameworks and web development best practices.",
        "Great to see so many passionate developers at this meetup – the networking opportunities and collaborations were top-notch!",
        "Can’t wait to learn more about how blockchain technology works and how it’s changing industries like finance and healthcare.",
        "I’m eager to learn more about UX/UI design principles to create more intuitive and user-friendly digital experiences.",
        "Looking forward to understanding the latest cybersecurity trends and learning how to keep my business secure in an increasingly digital world.",
        "This machine learning fundamentals course is exactly what I need to start exploring AI and data-driven solutions in my work.",
        "I’m looking forward to learning the latest strategies in digital marketing and how to effectively grow an online presence."
    ]
};

export default randomData;
